apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.17.9
          env:
            - name: node.name
              value: elasticsearch-node
            - name: cluster.name
              value: elasticsearch
            - name: discovery.type
              value: single-node
