apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: magento-storage