apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
          - containerPort: 3306
            name: db-port
          args:
          - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: root_password
            - name: MYSQL_DATABASE
              value: magentodb
            - name: MYSQL_USER
              value: magento
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: magento_db_password
          volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-data
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc