apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: magento-storage
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: true